development: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: eatabit_com_development
  min_messages: warning
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  username: postgres
  password:

test: &test
  <<: *default
  database: eatabit_com_test

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
